### ISSUE TITLE
Fix the arguments array inside the WP_Query call

### ISSUE THREAD

**Issue by xristos3490** [Yale-G/Flame-News-Post#1]
### Description

This line: 
https://github.com/Yale-G/Flame-News-Post/blob/1b75b0d65249563850d98835b1c6093d00910bed/includes/class-recent-widget.php#L36

`WP_Query` requires a specific way of handling it's arguments. 

These are dedicated arguments that will alter the results of the `WP_Query` query. You can see the documentation and sample code snippets here: https://developer.wordpress.org/reference/classes/wp_query/#parameters

### Resolution

Fix the `$args` array with a new `$query_args` array that utilizes all the query parameters needed for a successful `WP_Query` call

```php
$query_args = array( /* ... study the docs and procude a new array here that will fetch the last 5 posts ... */ );
$query = new WP_Query( $query_args );
```

**Comment by Yale-G** [comment]
### !! Done !!

- I've created the `$query_args` array, and inside I used `'post_in'`  

>   it returns `has_posts()` if passed and empty array inside, as true and displays all posts  

- also added the `'posts_per_page'` parameter and set it to 6. 

- deleted the previous loop

- styled the new loop elements (anchor, date etc)
